name: Azure OIDC Login

on:
  workflow_dispatch: # para lanzarlo manualmente al principio
  push:
    branches: [ "main" ]

permissions:
  id-token: write   # OBLIGATORIO para OIDC
  contents: read

jobs:
  login-to-azure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login via OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Verify login
        run: az account show
