name: CD Image Push to ACR

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Login a Azure usando OIDC
      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # 2. Login en Azure Container Registry
      - name: Azure Container Registry login (OIDC)
        run: |
          TOKEN=$(az acr login --name ${{ secrets.ACR_NAME }} --expose-token --output tsv --query accessToken)
          echo $TOKEN | docker login ${{ secrets.ACR_NAME }}.azurecr.io \
            --username 00000000-0000-0000-0000-000000000000 \
            --password-stdin


      # 3. Construir y pushear la imagen
      - name: Build and push image to ACR
        run: |
          IMAGE_TAG=${{ secrets.ACR_NAME }}.azurecr.io/${{ secrets.IMAGE_NAME }}:${{ github.sha }}
          docker build -f lab-be.dockerfile -t $IMAGE_TAG .
          docker push $IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      # 4. Obtener credenciales de AKS
      - name: Get AKS credentials
        run: |
          az aks get-credentials \
            --name ${{ secrets.AKS_NAME }} \
            --overwrite-existing \
            --resource-group ${{ secrets.RESOURCE_GROUP }}

      # 5. Desplegar en AKS
      - name: Deploy to AKS
        run: |
          # Suponiendo que tienes un manifiesto en k8s/deployment.yaml
          # y que usas la variable de la imagen como placeholder
          kubectl set image deployment/lab-be \
            lab-be=${{ env.IMAGE_TAG }} \
            --record
          kubectl rollout status deployment/lab-be
